### PR TITLE
Python 3 Compatibility and Relative Module Imports

### PR DESCRIPTION
**Pull request by jjangsangy**
Hey Rodrigo

So your library doesn't work on Python 3 and you use both relative and absolute imports in your module. This might work for you since you have your library installed, but it won't work for people who are installing your package.

I've patched up both of these issues in this PR.

Also I might recommend some refactoring so there is less code duplication in your packages. That way, you only need to patch up one location rather than 3.

### CODE REVIEW

**Comment by eugene-eeo** [comment]
Hi @jjangsangy, if you are interested in tools for extraction, would you consider giving [datalib/libextract](https://github.com/datalib/libextract) a look? It is more extensible and modular than eatihit, and is the successor to it.

**Comment by jjangsangy** [comment]
@eugene-eeo thanks for letting me know!

Mostly the reason I'm submitting the PR is due to some code that depends on `eatiht` and trying to get packages running on Python 3.

But in that case, I will let the package owners know so we try moving to `libextract`.

**Comment by jjangsangy** [comment]
Also @eugene-eeo, i'm looking at [libextract](https://github.com/datalib/libextract) and there are also similar issues in terms of Python 2 / 3 as well as usage of absolute imports for module packages.

I might help you guys out and send a PR, but currently don't have time in terms or looking through the new codebase and building everything so nothing is broken. But I would definitely suggest looking at [PEP 328: Imports: Multi-Line and Absolute/Relative](https://www.python.org/dev/peps/pep-0328/) as well as a [blog article](http://gehrcke.de/2014/02/distributing-a-python-command-line-application/) that will definitely better than I can explain.

**Comment by eugene-eeo** [comment]
@jjangsangy thanks, :+1: Will fix.

**Comment by eugene-eeo** [comment]
Does the latest build solve Python 2/3 compatibility? I have switched to relative imports for everything.

**Comment by jjangsangy** [comment]
Wait, did you just push code??

**Comment by jjangsangy** [comment]
Give me a sec, I'll check

**Comment by jjangsangy** [comment]
Ugh.. so I'll go to libextract, I don't want to continue discussion on this thread since it's off topic

**Comment by rodricios** [comment]
@eugene-eeo: thanks for taking of this!

**Comment by rodricios** [comment]
> [..] I will also let the package owners know so we try moving to `libextract`.

@jjangsangy please do! As I've said on eatiht's README, I'm moving most of my efforts to libextract.  

Just fyi, comprehensive sphynx documentation still missing (aside from docstrings), but that's one of the next things on my priority list. Thanks again for the pr

**Comment by jjangsangy** [comment]
Cool thanks!

Sphinx docs? I could help out setting up `sphinx-build`, and configuring the webhooks for building on [readthedocs](https://readthedocs.org/). The setup is pretty trivial in itself.

Hard part is documenting your API accurately, ensuring that the docs can be authoritative source of information. So that means figuring out which parts of your code to use as the public facing interfaces. I see that you guys are implementing strategy to generically swap algorithms. Each one of your strategies should have it's own interface and documentation. Actually I'm a little curious as to the implementations, if you want I could probably help build those interfaces if you show me how they're implemented ;)

**Comment by rodricios** [comment]
Absolutely! Still in the middle of work I have to finish at my uni, but
let's get ahold of each other via email and/or a new libextract issue?

**Comment by jjangsangy** [comment]
Sure thing, let me know.

Sang Han: jjangsangy@gmail.com

**Pull request merged**
