### PR TITLE
Uses Chardet to Detect HTML Encoding rather than assume UTF-8

### PR DESCRIPTION
**Pull request by jjangsangy**
# Fix for Text Encoding Bugs

1. Adds the `chardet` package as a requirement.
    - The `chardet` library analyzes site content using to detect the correct encoding scheme.
    - https://github.com/rodricios/eatiht/compare/master...jjangsangy:master#diff-e88728a5c6b56a196273fe1ba7c12382R148
2. Fixes this issue https://github.com/rodricios/eatiht/issues/14 .
    - Even when `bom` tag is set incorrectly by the author.
3. May also resolve https://github.com/rodricios/eatiht/issues/13 where incorrect encoding results in `UnicodeDecodeErrror` exception.
4. Now supports both HTTP and HTTPS sites. 

encoding

### CODE REVIEW

**Comment by jjangsangy** [comment]
Awesome!

**Comment by jjangsangy** [comment]
Also, I would definitely love to use your package on more platforms other than CLI. Wanted to ask if it would be alright to have this package installed at [blockspring](https://api.blockspring.com), so that's it's available for people in that community to use as well!

I've already talked to blockspring and they all seem pretty interested in having your module on their stack!

Thanks!

**Comment by rodricios** [comment]
Absolutely! There's no way I'm saying no to that! 

First time I've actually heard of blockspring. Seems like a neat platform and concept. Found their jobs section; do they mainly write wrappers in Ruby? Not sure if you're the person to ask though lol. In any case, thanks for informing me!

**Comment by jjangsangy** [comment]
Hmmm.. Dunno actually. You should definitely go ask them!

**Comment by pkpp1233** [comment]
Blockspring functions can be in ruby, r, python, php, and node for now... more languages to come :).

PS - I just enabled eatiht. Your library looks awesome!!

**Comment by rodricios** [comment]
Hi @pkpp1233! Thanks for including my library, definitely going to include that in my portfolio/resume :P

**Pull request merged**
